// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function setStorage(val) {
  return chrome.storage.local.set(val);
}

function getStorage(key) {
  return chrome.storage.local.get(key);
}

chrome.runtime.onInstalled.addListener(function (param) {
      console.log("Initialising then retrieving state");
      return setStorage({
                      state: "My State Value"
                    }).then(function () {
                    return getStorage("state");
                  }).then(function (res) {
                  console.log(res);
                });
    });

chrome.webNavigation.onCompleted.addListener(function (navEvent) {
      console.log("Naving");
      console.log(navEvent.timeStamp);
    });

chrome.tabs.onActivated.addListener(function (tabInfo) {
      console.log("Tabbing");
      console.log(tabInfo.tabId);
      console.log(tabInfo.windowId);
    });

exports.setStorage = setStorage;
exports.getStorage = getStorage;
/*  Not a pure module */
