// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


chrome.runtime.onInstalled.addListener(function () {
      console.log("Initialising state then retrieving it");
      chrome.storage.local.set({
              state: "My State Value"
            }).then(function () {
            return chrome.storage.local.get("state").then(function (res) {
                        console.log(res.state);
                      });
          });
    });

chrome.webNavigation.onCompleted.addListener(function (navEvent) {
      console.log("Naving");
      console.log(navEvent);
    });

chrome.tabs.onActivated.addListener(function (tabInfo) {
      console.log("Tabbing");
      console.log(tabInfo);
    });

chrome.tabs.onRemoved.addListener(function (id, tabRemoveInfo) {
      console.log("Closing");
      console.log(id);
      console.log(tabRemoveInfo);
    });

/*  Not a pure module */
